### ISSUE TITLE
Swapping master and slave and setting up new master/slave replication

### ISSUE THREAD

**Issue by charl** [siddontang/ledisdb#280]
We had a ledis master/slave setup that was replicating fine.

We recently experienced some data corruption on the master so we took it down and promoted the slave to be the new master.

Replication now no longer works between the new master and the old master (which is now the slave). The new slave had all its prior data removed and should just function like a brand new ledis slave node.

On the new master:

```
10.0.0.208:6380> info replication
# Replication
role:master
pub_log_num:0
pub_log_ack_per_time:0
slaveof:
slaves:10.0.0.99:6380
last_log_id:4102189945
first_log_id:4050241982
commit_log_id:4102189945
master_last_log_id:0
```

On the new slave:

```
10.0.0.99:6380> info replication
# Replication
role:slave
pub_log_num:0
pub_log_ack_per_time:0
slaveof:10.0.0.208:6380
last_log_id:0
first_log_id:0
commit_log_id:0
master_last_log_id:0
master_link_status:up
slave_priority:100
slave_repl_offset:0
```

Is there some additional tasks required to set up replication in this case?

**Comment by siddontang** [comment]
Hi @charl 

Any log in current new master and slave. Is master sending snapshot to the slave?

**Comment by charl** [comment]
On the master:

```
$ ls -la /mnt/volume-sfo2-06/var/lib/ledis/rpl/
total 16
drwxr-xr-x 3 root root 4096 Feb 15 10:53 .
drwxr-xr-x 5 root root 4096 Mar  5 15:53 ..
-rw-r--r-- 1 root root    8 Mar  9 09:29 commit.log
drwxr-xr-x 2 root root 4096 Mar  9 09:24 ldb
$ ls -la /mnt/volume-sfo2-06/var/lib/ledis/rpl/ldb/
total 13182800
drwxr-xr-x 2 root root      4096 Mar  9 09:24 .
drwxr-xr-x 3 root root      4096 Feb 15 10:53 ..
-rw-r--r-- 1 root root 268435588 Mar  3 00:11 00003838.data
-rw-r--r-- 1 root root   4232644 Mar  3 00:11 00003838.meta
[...]
-rw-r--r-- 1 root root 238678131 Mar  9 09:54 00003888.data
-rw-r--r-- 1 root root   3739440 Mar  9 09:54 00003888.meta
```

On the slave:

```
$ ls -la /mnt/volume-sfo2-02/var/lib/ledis/leveldb_data/
total 24
drwxr-xr-x 2 root root 4096 Mar 11 05:48 .
drwxrwxr-x 5 root root 4096 Mar  9 09:29 ..
-rw-r--r-- 1 root root    0 Mar 11 05:48 000013.log
-rw-r--r-- 1 root root   16 Mar 11 05:48 CURRENT
-rw-r--r-- 1 root root    0 Mar  9 08:30 LOCK
-rw-r--r-- 1 root root  175 Mar 11 05:48 LOG
-rw-r--r-- 1 root root  172 Mar  9 09:00 LOG.old
-rw-r--r-- 1 root root   50 Mar 11 05:48 MANIFEST-000012
$ ls -la /mnt/volume-sfo2-02/var/lib/ledis/rpl/
total 16
drwxr-xr-x 3 root root 4096 Mar  9 08:38 .
drwxrwxr-x 5 root root 4096 Mar  9 09:29 ..
-rw-r--r-- 1 root root    8 Mar 14 08:49 commit.log
drwxr-xr-x 2 root root 4096 Mar  9 08:38 ldb
$ ls -la /mnt/volume-sfo2-02/var/lib/ledis/rpl/ldb/
total 8
drwxr-xr-x 2 root root 4096 Mar  9 08:38 .
drwxr-xr-x 3 root root 4096 Mar  9 08:38 ..
```

Here's the traffic I see on the master to the slave:

```
$ sudo tcpdump -i eth0 -X -s 2048 host 10.0.0.99 and dst port 6380
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 2048 bytes



08:55:31.085191 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [P.], seq 2270108330:2270108344, ack 1622922997, win 229, length 14
  0x0000:  4500 0036 db76 4000 3f06 4f0e 8a44 3863  E..6.v@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1aaa 60bb d6f5  .........O..`...
  0x0020:  5018 00e5 de6a 0000 2a31 0d0a 2434 0d0a  P....j..*1..$4..
  0x0030:  5049 4e47 0d0a                           PING..
08:55:31.086324 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [.], ack 8, win 229, length 0
  0x0000:  4500 0028 db77 4000 3f06 4f1b 8a44 3863  E..(.w@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1ab8 60bb d6fc  .........O..`...
  0x0020:  5010 00e5 f27f 0000 0000                 P.........
08:55:31.086398 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [P.], seq 14:63, ack 8, win 229, length 49
  0x0000:  4500 0059 db78 4000 3f06 4ee9 8a44 3863  E..Y.x@.?.N..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1ab8 60bb d6fc  .........O..`...
  0x0020:  5018 00e5 e424 0000 2a33 0d0a 2438 0d0a  P....$..*3..$8..
  0x0030:  7265 706c 636f 6e66 0d0a 2431 340d 0a6c  replconf..$14..l
  0x0040:  6973 7465 6e69 6e67 2d70 6f72 740d 0a24  istening-port..$
  0x0050:  340d 0a36 3338 300d 0a                   4..6380..
08:55:31.123268 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [.], ack 35, win 229, length 0
  0x0000:  4500 0028 db79 4000 3f06 4f19 8a44 3863  E..(.y@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1ae9 60bb d717  .........O..`...
  0x0020:  5010 00e5 f233 0000 0000                 P....3....
08:55:41.087286 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [P.], seq 63:77, ack 35, win 229, length 14
  0x0000:  4500 0036 db7a 4000 3f06 4f0a 8a44 3863  E..6.z@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1ae9 60bb d717  .........O..`...
  0x0020:  5018 00e5 de09 0000 2a31 0d0a 2434 0d0a  P.......*1..$4..
  0x0030:  5049 4e47 0d0a                           PING..
08:55:41.087718 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [.], ack 42, win 229, length 0
  0x0000:  4500 0028 db7b 4000 3f06 4f17 8a44 3863  E..(.{@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1af7 60bb d71e  .........O..`...
  0x0020:  5010 00e5 f21e 0000 0000                 P.........
08:55:41.087746 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [P.], seq 77:126, ack 42, win 229, length 49
  0x0000:  4500 0059 db7c 4000 3f06 4ee5 8a44 3863  E..Y.|@.?.N..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1af7 60bb d71e  .........O..`...
  0x0020:  5018 00e5 e3c3 0000 2a33 0d0a 2438 0d0a  P.......*3..$8..
  0x0030:  7265 706c 636f 6e66 0d0a 2431 340d 0a6c  replconf..$14..l
  0x0040:  6973 7465 6e69 6e67 2d70 6f72 740d 0a24  istening-port..$
  0x0050:  340d 0a36 3338 300d 0a                   4..6380..
08:55:41.127149 IP 10.0.0.99.47238 > 10.0.0.208.6380: Flags [.], ack 69, win 229, length 0
  0x0000:  4500 0028 db7d 4000 3f06 4f15 8a44 3863  E..(.}@.?.O..D8c
  0x0010:  8ac5 c3d0 b886 18ec 874f 1b28 60bb d739  .........O.(`..9
  0x0020:  5010 00e5 f1d2 0000 0000                 P.........
[...]
```

**Comment by siddontang** [comment]
Sorry for the late response, @charl 

Any sync log message in the log file? Can you show me the log?

How about run `fullsync` in the slave, can it still work? 

Sincerely, the replication code is very ugly and I have to consider to refactor it all.

**Comment by charl** [comment]
When I try to start the new master with _-rpl_ it panics:

```
# /usr/local/bin/ledis-server -rpl -config=/etc/ledis/ledis.conf
panic: runtime error: index out of range

goroutine 27 [running]:
github.com/siddontang/ledisdb/store/leveldb.(*WriteBatch).Delete(0xc8201c79e0, 0xc82022e42e, 0x0, 0x106)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:58 +0x49
github.com/siddontang/ledisdb/store.(*WriteBatch).Delete(0xc8201f3d00, 0xc82022e42e, 0x0, 0x106)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:33 +0x5c
github.com/syndtr/goleveldb/leveldb.(*Batch).Replay.func1(0x1, 0x0, 0xc82022e42e, 0x0, 0x106, 0x0, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:129 +0x5f
github.com/syndtr/goleveldb/leveldb.(*Batch).decodeRec(0xc82026a6c0, 0xc820034d58, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:227 +0x33f
github.com/syndtr/goleveldb/leveldb.(*Batch).Replay(0xc82026a6c0, 0x7f73bc778738, 0xc8201f3d00, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:131 +0x53
github.com/siddontang/ledisdb/store.(*BatchData).Replay(0xc82026a6c0, 0x7f73bc778708, 0xc8201f3d00, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:140 +0x74
github.com/siddontang/ledisdb/ledis.(*Ledis).handleReplication(0xc8201b0240, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/replication.go:58 +0x70c
github.com/siddontang/ledisdb/ledis.(*Ledis).onReplication(0xc8201b0240)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/replication.go:86 +0xf5
created by github.com/siddontang/ledisdb/ledis.Open
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/ledis.go:83 +0x46f

goroutine 1 [runnable]:
github.com/siddontang/ledisdb/ledis.(*Ledis).WaitReplication(0xc8201b0240, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/replication.go:102 +0x2b4
github.com/siddontang/ledisdb/ledis.Open(0xc8200b2780, 0xc8201a56e0, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/ledis.go:87 +0x47d
github.com/siddontang/ledisdb/server.NewApp(0xc8200b2780, 0x1d, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/app.go:120 +0x81a
main.main()
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/cmd/ledis-server/main.go:92 +0x4d4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [select]:
github.com/siddontang/go/log.(*Logger).run(0xc82006a150)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/siddontang/go/log/log.go:100 +0x269
created by github.com/siddontang/go/log.New
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/siddontang/go/log/log.go:80 +0x1cc

goroutine 24 [select]:
github.com/siddontang/ledisdb/server.(*snapshotStore).run(0xc8201a56e0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/snapshot.go:115 +0x2c3
created by github.com/siddontang/ledisdb/server.newSnapshotStore
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/snapshot.go:67 +0x2fb

goroutine 25 [select]:
github.com/siddontang/ledisdb/rpl.(*FileStore).checkTableReaders(0xc82006a460)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/rpl/file_store.go:285 +0x338
created by github.com/siddontang/ledisdb/rpl.NewFileStore
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/rpl/file_store.go:97 +0x298

goroutine 26 [select]:
github.com/siddontang/ledisdb/rpl.(*Replication).run(0xc82006e720)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/rpl/rpl.go:298 +0x796
created by github.com/siddontang/ledisdb/rpl.NewReplication
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/rpl/rpl.go:78 +0x5da
```

**Comment by charl** [comment]
I built a new version of the server from master and I get this on the master when starting it up with *-rpl*:

```
# /var/tmp/ledis-server -rpl -config=/etc/ledis/ledis.conf
panic: runtime error: index out of range

goroutine 10 [running]:
github.com/siddontang/ledisdb/store/leveldb.(*WriteBatch).Delete(0xc420237ce0, 0xc42028042e, 0x0, 0x106)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:58 +0x57
github.com/siddontang/ledisdb/store.(*WriteBatch).Delete(0xc42024e100, 0xc42028042e, 0x0, 0x106)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:33 +0x5c
github.com/syndtr/goleveldb/leveldb.(*Batch).Replay.func1(0x1, 0x0, 0xc42028042e, 0x0, 0x106, 0x0, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/syndtr/goleveldb/leveldb/batch.go:129 +0xb6
github.com/syndtr/goleveldb/leveldb.(*Batch).decodeRec(0xc4202c0a40, 0xc420037d60, 0x410f58, 0xa2e300)
	/home/charl/projects/go/src/github.com/syndtr/goleveldb/leveldb/batch.go:227 +0x17d
github.com/syndtr/goleveldb/leveldb.(*Batch).Replay(0xc4202c0a40, 0x7f78701da330, 0xc42024e100, 0x7f78701da330, 0xc42024e100)
	/home/charl/projects/go/src/github.com/syndtr/goleveldb/leveldb/batch.go:131 +0x67
github.com/siddontang/ledisdb/store.(*BatchData).Replay(0xc4202c0a40, 0xfb68c0, 0xc42024e100, 0xc4202c0a40, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:140 +0x6a
github.com/siddontang/ledisdb/ledis.(*Ledis).handleReplication(0xc4201f6240, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/replication.go:58 +0x1b0
github.com/siddontang/ledisdb/ledis.(*Ledis).onReplication(0xc4201f6240)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/replication.go:86 +0x102
created by github.com/siddontang/ledisdb/ledis.Open
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/ledis.go:83 +0x408
```

**Comment by siddontang** [comment]
oh, bad news. 

I will see it later.

**Comment by siddontang** [comment]
Hi @charl 

I use the newest master but can't reproduce this error. Do you have any old replication data?

**Comment by charl** [comment]
If I stop the master, move the rpl to rpl.off and start the master back up with the *-rpl* switch I get:

```
[2017/03/17 12:36:44] client_resp.go:101 [Fatal] client run panic goroutine 81 [running]:
github.com/siddontang/ledisdb/server.(*respClient).run.func1(0xc420245020)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/client_resp.go:98 +0x139
panic(0xa24860, 0xc420191490)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/siddontang/ledisdb/store/leveldb.(*WriteBatch).Data.func1(0x1f6bee0, 0xc420234140)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:100 +0x8b
github.com/siddontang/ledisdb/store/leveldb.(*WriteBatch).Data(0xc4202380a0, 0x40523c, 0xfe2720, 0xc420039c68)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/leveldb/batch.go:102 +0x64
github.com/siddontang/ledisdb/store.(*WriteBatch).BatchData(0xc420234100, 0x1f6bee0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:65 +0x37
github.com/siddontang/ledisdb/store.(*WriteBatch).Data(0xc420234100, 0x7adf3c, 0x1f6bee0, 0xc420116690)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/store/writebatch.go:75 +0x2b
github.com/siddontang/ledisdb/ledis.(*Ledis).handleCommit(0xc4201e0240, 0xfb33c0, 0xc420234100, 0xfb3400, 0xc420234100, 0x1, 0x8)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/batch.go:108 +0x7d
github.com/siddontang/ledisdb/ledis.(*batch).Commit(0xc4202380c0, 0xc420116690, 0x69)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/batch.go:26 +0x97
github.com/siddontang/ledisdb/ledis.(*DB).incr(0xc42024c000, 0xc420116620, 0x67, 0x67, 0x1, 0x0, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/t_kv.go:93 +0x2c9
github.com/siddontang/ledisdb/ledis.(*DB).IncrBy(0xc42024c000, 0xc420116620, 0x67, 0x67, 0x1, 0x1, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/ledis/t_kv.go:220 +0x53
github.com/siddontang/ledisdb/server.incrbyCommand(0xc42030a580, 0xc4201a24e0, 0xc420191458)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/cmd_kv.go:163 +0xbe
github.com/siddontang/ledisdb/server.(*client).perform(0xc42030a580)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/client.go:134 +0x267
github.com/siddontang/ledisdb/server.(*respClient).handleRequest(0xc420245020, 0xc420056dc0, 0x3, 0x3, 0x0, 0x0)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/client_resp.go:185 +0x102
github.com/siddontang/ledisdb/server.(*respClient).run(0xc420245020)
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/client_resp.go:139 +0x217
created by github.com/siddontang/ledisdb/server.newClientRESP
	/home/charl/projects/go/src/github.com/siddontang/ledisdb/server/client_resp.go:91 +0x353
:runtime error: cgo argument has Go pointer to Go pointer
```

**Comment by siddontang** [comment]
very strange. can you run a new and clean ledis-server and do something?

**Comment by siddontang** [comment]
Hi @charl 

What's the git commit version? do you use the latest ?

**Comment by charl** [comment]
Confirmed fixed.

**Comment by charl** [comment]
Thanks for all your hard work @siddontang!
